export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
export const REMOVE_PRODUCT_FROM_CART = "REMOVE_PRODUCT_FROM_CART";
export const ADD_UNITS = "ADD_UNITS";
export const SUBTRACT_UNITS = "SUBTRACT_UNITS";
